up:
	docker compose up -d
stop:
	docker compose stop
build:
	docker compose build
down:
	docker compose down --volume --remove-orphans
ps:
	docker compose ps
log:
	docker compose logs api
exec:
	docker compose exec api bash
