up:
	docker compose up -d
build:
	docker compose build
stop:
	docker compose stop
down:
	docker compose down
exec:
	docker compose exec scraper bash
ps:
	docker compose ps
log:
	docker compose logs scraper
